/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SEABIRD_SHELL_COMPILE_PRIVATE_H
#define SEABIRD_SHELL_COMPILE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"4.1.0.254"
#define VER_MAJOR	4
#define VER_MINOR	1
#define VER_RELEASE	0
#define VER_BUILD	254
#define COMPANY_NAME	""
#define FILE_VERSION	"4.1.0.254"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Seabird Galactic Shell"
#define PRODUCT_VERSION	"4.1.0.254"

#endif /*SEABIRD_SHELL_COMPILE_PRIVATE_H*/
